# Generated by Django 4.2.7 on 2026-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='product image'),
        ),
    ]
