# Generated by Django 4.2.7 on 2026-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='buy price'),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('Rent', 'Rent Only'), ('Buy', 'Buy Only'), ('Both', 'Rent & Buy')], default='Rent', max_length=4, verbose_name='listing type'),
        ),
    ]
