# Generated by Django 4.2.7 on 2026-05-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_product_buy_price_product_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_products', to='rental.customer', verbose_name='posted by'),
        ),
    ]
