# Generated by Django 4.2.7 on 2026-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_product_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='student id'),
        ),
        migrations.AddField(
            model_name='customer',
            name='university_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='university name'),
        ),
    ]
