# Generated by Django 4.2.7 on 2026-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_customer_student_id_customer_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Housing', 'Housing')], db_index=True, max_length=20, verbose_name='category'),
        ),
    ]
