# Generated by Django 4.2.7 on 2026-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='avatar URL'),
        ),
    ]
