# Generated by Django 4.2.7 on 2026-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ac_included',
            field=models.BooleanField(default=False, verbose_name='AC included'),
        ),
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='bathrooms'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='product',
            name='flat_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='flat size (sqft)'),
        ),
        migrations.AddField(
            model_name='product',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='furnished'),
        ),
        migrations.AddField(
            model_name='product',
            name='house_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='house type'),
        ),
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per day'),
        ),
    ]
